---
- name: "Init broker with default values."
  set_fact:
    _broker:
      name: "{{ broker.name }}"
      path: "{{ broker.path }}"
      user: "{{ broker.user }}"
      password: "{{ broker.password }}"
      host: "{{ broker.host | default(artemis_host) }}"
      acceptors: "{{ broker.acceptors | default(artemis_acceptors) }}"

- name: "Create broker {{ _broker.name }}"
  artemis_create:
    name: "{{ _broker.path }}/{{ _broker.name }}"
    user: "{{ _broker.user }}"
    password: "{{ _broker.password }}"

- name: "Update owner / group for broker folder"
  file:
    path: "{{ _broker.path }}/{{ _broker.name }}"
    state: directory
    mode: 0755
    recurse: true
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: "Configure {{ _broker.name }}"
  template:
    src: "artemis/etc/broker.xml"
    dest: "{{ _broker.path }}/{{ _broker.name }}/etc/broker.xml"

- name: "Install broker as service"
  include: service.yml
