---
- name: "Create broker {{ broker.name }}"
  artemis_create:
    name: "{{ broker.path }}"
    user: "{{ broker.user }}"
    password: "{{ broker.password }}"

- name: "Update owner / group for broker folder"
  file:
    path: "{{ broker.path }}/{{ broker.name }}"
    state: directory
    mode: 0755
    recurse: true
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: "Install {{ broker.name }} as service"
  template:
    src: "etc/systemd/artemis.service"
    dest: "/etc/systemd/system/{{ broker.name }}.service"
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: "Configure {{ broker.name }}"
  template:
    src: "artemis/etc/broker.xml"
    dest: "{{ broker.path }}/{{ broker.name }}/etc/broker.xml"

- name: "Enable service"
  service:
    name: "{{ broker.name }}"
    enabled: yes
    state: "started"
