---
- name: "Add Artemis group"
  group:
    name: "{{ artemis_group }}"

- name: "Add Artemis user"
  user:
    name: "{{ artemis_user }}"
    group: "{{ artemis_group }}"
    createhome: no
    state: present
    system: yes

- name: "Create requires directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"
  with_items:
    - "{{ artemis_home }}"
#   - "{{ artemis_log_dir }}"


- name: "Download and extract archive"
  unarchive:
    src: "{{ artemis_download_url }}"
    dest: "{{ artemis_home }}"
    remote_src: yes
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: "Create link"
  file:
    src: "{{ artemis_home }}/apache-artemis-{{ artemis_version }}"
    dest: "{{ artemis_home }}/artemis"
    state: link
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: "Create brokers"
  include: broker.yml
  with_items: "{{ artemis_brokers }}"
  loop_control:
    loop_var: broker
