---
- name: "os-specific vars"
  include_vars: "{{ansible_os_family}}.yml"

- include: java.yml
  when: artemis_java_install

- name: "Add Artemis group"
  group:
    name: "{{ artemis_group }}"

- name: "Add Artemis user"
  user:
    name: "{{ artemis_user }}"
    group: "{{ artemis_group }}"
    createhome: no
    state: present
    system: yes

- name: "Create requires directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"
  with_items:
  - "{{ artemis_home }}"
#  - "{{ artemis_log_dir }}"


- name: "Download and extract archive"
  unarchive:
    src: "{{ artemis_download_url }}"
    dest: "{{ artemis_home }}"
    remote_src: yes
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}"

- name: "Create link"
  file:
    src: "{{ artemis_home }}/apache-artemis-{{ artemis_version }}"
    dest: "{{ artemis_home }}/artemis"
    state: link
    owner: "{{ artemis_user }}"
    group: "{{ artemis_group }}

# Create instances :  ./artemis create var/lib/mybroker --user admin --password admin --allow-anonymous | --require-login: is a mandatory property